# -*- coding: utf-8 -*-
"""Chilli_Analysis(PvsR).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTTu2CaHxEM4yXeSYr6nU2hSCsbEHgnO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the CSV
df = pd.read_csv('chilli_rainfall_cleaned.csv')

# See the first 5 rows
df.head()

# How many rows and columns?
print("Shape:", df.shape)

# Column names and data types
df.info()

# Any missing values?
df.isnull().sum()

# Quick statistical summary
df.describe()

missing_rainfall = df[df['annual_rainfall_mm'].isnull()]
print(missing_rainfall)

zero_rows = df[(df['Area(HA)'] == 0) | (df['Production(MT)'] == 0) | (df['Yield'] == 0)]
print(zero_rows)

df['annual_rainfall_mm'] = df.groupby('State')['annual_rainfall_mm'].transform(
    lambda x: x.fillna(x.mean())
)

# Confirm no more missing values
df.isnull().sum()

df['Year_num'] = df['Year'].str[:4].astype(int)
df[['Year', 'Year_num']].head()

print("Duplicate rows:", df.duplicated().sum())

df.to_csv('chilli_rainfall_cleaned.csv', index=False)

from google.colab import files
files.download('chilli_rainfall_cleaned.csv')

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('chilli_rainfall_cleaned.csv')
df.head()

df_active = df[df['Production(MT)'] > 0].copy()

print("Total rows:", len(df))
print("Rows with actual chilli production:", len(df_active))

top_states = df_active.groupby('State')['Production(MT)'].sum().sort_values(ascending=False)
print(top_states.head(10))

rainfall_by_state = df_active.groupby('State')['annual_rainfall_mm'].mean().sort_values(ascending=False)
print(rainfall_by_state.head(5))   # wettest
print(rainfall_by_state.tail(5))   # driest

yearly_trend = df_active.groupby('Year_num')[['Yield', 'annual_rainfall_mm']].mean()
print(yearly_trend)

df_active['Yield'].describe()

outlier_row = df_active.sort_values('Yield', ascending=False).head(3)
print(outlier_row[['State','Year','Area(HA)','Production(MT)','Yield']])

# Ranking by Area
top_by_area = df_active.groupby('State')['Area(HA)'].sum().sort_values(ascending=False)
print("Top 10 by Area:")
print(top_by_area.head(10))

# Ranking by Production
top_by_production = df_active.groupby('State')['Production(MT)'].sum().sort_values(ascending=False)
print("\nTop 10 by Production:")
print(top_by_production.head(10))

# Ranking by average Yield (efficiency, not just size)
top_by_yield = df_active.groupby('State')['Yield'].mean().sort_values(ascending=False)
print("\nTop 10 by average Yield (efficiency):")
print(top_by_yield.head(10))



correlation_overall = df_active['annual_rainfall_mm'].corr(df_active['Yield'])
print("Overall correlation (Rainfall vs Yield):", correlation_overall)

cols_to_check = ['annual_rainfall_mm', 'Area(HA)', 'Production(MT)', 'Yield']
correlation_matrix = df_active[cols_to_check].corr()
print(correlation_matrix)

state_correlations = df_active.groupby('State').apply(
    lambda x: x['annual_rainfall_mm'].corr(x['Yield']) if len(x) > 1 else None
).sort_values(ascending=False)

print(state_correlations)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.scatter(df_active['annual_rainfall_mm'], df_active['Yield'], alpha=0.6)
plt.xlabel('Annual Rainfall (mm)')
plt.ylabel('Yield (tonnes/hectare)')
plt.title('Rainfall vs Yield — All States, All Years')
plt.show()

import matplotlib.pyplot as plt

# Recalculate and drop the NaN (Andaman & Nicobar) since it can't be plotted
state_correlations = df_active.groupby('State').apply(
    lambda x: x['annual_rainfall_mm'].corr(x['Yield']) if len(x) > 1 else None
).dropna().sort_values()

plt.figure(figsize=(8, 10))
colors = ['crimson' if v < 0 else 'seagreen' for v in state_correlations]
plt.barh(state_correlations.index, state_correlations.values, color=colors)
plt.axvline(0, color='black', linewidth=0.8)
plt.xlabel('Correlation (Rainfall vs Yield)')
plt.title('Which States Benefit from Rain, and Which Don\'t')
plt.tight_layout()
plt.show()

import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(data=df_active, x='annual_rainfall_mm', y='Yield', hue='State', legend=False, alpha=0.7, s=80)
plt.xlabel('Annual Rainfall (mm)')
plt.ylabel('Yield (tonnes/hectare)')
plt.title('Rainfall vs Yield — Colored by State')
plt.show()

plt.figure(figsize=(6, 5))
cols_to_check = ['annual_rainfall_mm', 'Area(HA)', 'Production(MT)', 'Yield']
sns.heatmap(df_active[cols_to_check].corr(), annot=True, cmap='coolwarm', center=0, fmt='.2f')
plt.title('Correlation Heatmap: Rainfall, Area, Production, Yield')
plt.show()

top5_states = df_active.groupby('State')['Production(MT)'].sum().sort_values(ascending=False).head(10).index

plt.figure(figsize=(9, 6))
for state in top5_states:
    subset = df_active[df_active['State'] == state].sort_values('Year_num')
    plt.plot(subset['Year_num'], subset['Yield'], marker='o', label=state)

plt.xlabel('Year')
plt.ylabel('Yield (tonnes/hectare)')
plt.title('Yield Trend (2020–2024) — Top 5 Producing States')
plt.legend()
plt.show()

import os
os.makedirs('charts', exist_ok=True)

# Re-run each plot but save instead of just show, e.g.:
plt.savefig('charts/yield_trend_top5.png', dpi=150, bbox_inches='tight')

from sklearn.model_selection import train_test_split

# Features (inputs) and target (what we're predicting)
features = ['Area(HA)', 'annual_rainfall_mm']
target = 'Yield'

X = df_active[features]
y = df_active[target]

# Split into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

print("Linear Regression R²:", r2_score(y_test, y_pred_lr))
print("Linear Regression RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

df[df['State'] == 'Andaman & Nicobar'][['State', 'Year', 'annual_rainfall_mm']]

# Step 1: fill with state's own average (already done, but re-run safely)
df['annual_rainfall_mm'] = df.groupby('State')['annual_rainfall_mm'].transform(
    lambda x: x.fillna(x.mean())
)

# Step 2: any states that were fully NaN (like Andaman & Nicobar) still remain --
# fill those remaining gaps with the overall national average
df['annual_rainfall_mm'] = df['annual_rainfall_mm'].fillna(df['annual_rainfall_mm'].mean())

# Confirm no NaNs remain anywhere
print(df.isnull().sum())

df_active = df[df['Production(MT)'] > 0].copy()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

print("Linear Regression R²:", r2_score(y_test, y_pred_lr))
print("Linear Regression RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Random Forest R²:", r2_score(y_test, y_pred_rf))
print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

importance = pd.Series(rf_model.feature_importances_, index=features).sort_values(ascending=False)
print(importance)

df.to_csv('chilli_rainfall_final.csv', index=False)

from google.colab import files
files.download('chilli_rainfall_final.csv')

"""# New Section"""

state_correlations = df_active.groupby('State').apply(
    lambda x: x['annual_rainfall_mm'].corr(x['Yield']) if len(x) > 1 else None
).reset_index()

state_correlations.columns = ['State', 'Rainfall_Yield_Correlation']
state_correlations = state_correlations.dropna()

state_correlations.to_csv('state_correlations.csv', index=False)

from google.colab import files
files.download('state_correlations.csv')

